[theme]
primaryColor = "#E63946"
backgroundColor = "#0B1D3A"
secondaryBackgroundColor = "#132744"
textColor = "#FCEEA7"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
